### ISSUE TITLE
Could not install robotgo in MacOS Sierra using Go 1.10.1

### ISSUE THREAD

**Issue by antonioaguilar** [go-vgo/robotgo#134]
- Robotgo version (or commit ref):
- Go version: 1.10.1
- Gcc version: n/a
- Operating system and bit: MacOS Sierra (10.12.6)
- Can you reproduce the bug at [Examples](https://github.com/go-vgo/robotgo/blob/master/examples/main.go):
  - [ ] Yes (provide example code)
  - [ ] No
  - [X ] Not relevant
- Provide example code: `go get -v github.com/go-vgo/robotgo`
- Log gist:

```
robotgo$ go get -v github.com/go-vgo/robotgo
github.com/go-vgo/robotgo
# github.com/go-vgo/robotgo
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(png.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngread.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwrite.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngmem.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngget.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngset.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngtrans.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngerror.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwio.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrio.o)) was built for newer OSX version (10.13) than being linked (10.12)
Undefined symbols for architecture x86_64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in libpng.a(pngrutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
## Description

Could not install `robotgo` go library via `go get -v github.com/go-vgo/robotgo` and therefore could not run the basic examples.

**Comment by vcaesar** [comment]
Please see #102, #128 or upgrade the system, I don't have a 10.12 system, you can use
```
brew install zlib
brew install libpng
```
to compile libpng and replace` libpng.a`.

**Comment by antonioaguilar** [comment]
@vcaesar installing `zlib` and `libpng` still didn't work on macOS Sierra 10.12.6.  Getting the same warning: `libpng.a(png.o)) was built for newer OSX version (10.13) than being linked (10.12) ...`. any other suggestions on how to proceed?

**Comment by vcaesar** [comment]
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`? I changed the cmake compilation, ignore the useless warning if the program executes normally.

**Comment by antonioaguilar** [comment]
@vcaesar I'm trying to run the basic mouse example, doing a `go get` or `go build` or `go run` does not work. This is the entire error log: 

```
aaguilar@mbp:robotgo$ cat mouse.go
package main

import (
  "github.com/go-vgo/robotgo"
)

func main() {
  robotgo.ScrollMouse(10, "up")
  robotgo.ScrollMouse(20, "down")
  robotgo.MouseClick("left", true)
  robotgo.MoveMouseSmooth(100, 200, 1.0, 100.0)
}
aaguilar@mbp:robotgo$ go get -u -v github.com/go-vgo/robotgo
github.com/go-vgo/robotgo (download)
github.com/go-vgo/robotgo
# github.com/go-vgo/robotgo
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(png.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngread.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwrite.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngmem.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngget.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngset.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngtrans.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngerror.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwio.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrio.o)) was built for newer OSX version (10.13) than being linked (10.12)
Undefined symbols for architecture x86_64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in libpng.a(pngrutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
aaguilar@mbp:robotgo$ go build -v mouse.go
github.com/go-vgo/robotgo
# github.com/go-vgo/robotgo
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(png.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngread.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwrite.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngmem.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngget.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngset.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngtrans.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngerror.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwio.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwutil.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngwtran.o)) was built for newer OSX version (10.13) than being linked (10.12)
ld: warning: object file (/Users/aaguilar/.gvm/pkgsets/go1.10.1/global/src/github.com/go-vgo/robotgo/cdeps/mac/libpng.a(pngrio.o)) was built for newer OSX version (10.13) than being linked (10.12)
Undefined symbols for architecture x86_64:
  "_inflateValidate", referenced from:
      _png_inflate_claim in libpng.a(pngrutil.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vcaesar** [comment]
If your code is up to date, try removing the [#L27](https://github.com/go-vgo/robotgo/blob/master/robotgo.go#L27) and [#L29](https://github.com/go-vgo/robotgo/blob/master/robotgo.go#L29) comments (just delete //). Of course, you can also compile the .a file yourself, expect your reply.

**Comment by antonioaguilar** [comment]
Do you want me to build the `robotgo` code locally? At the moment I'm trying to do it via: `go get -u -v github.com/go-vgo/robotgo` which should install the library from your repo.

**Comment by vcaesar** [comment]
I am verifyed normal operation on macos 10.13 and 10.10, please update it, there is no problem in theory. If you have any problems in other versions, please compile libpng.a yourself. This is a very simple operation.

**Comment by vcaesar** [comment]
I am verifyed normal operation on macos 10.13 and 10.10, please update it, there is no problem in theory. If you have any problems in other versions, please compile libpng.a yourself. This is a very simple operation.

**Comment by antonioaguilar** [comment]
This is the `libpng` version I'm using: 
```
brew info libpng
libpng: stable 1.6.35 (bottled), HEAD
```
what version of `libpng.a` should I use?

**Comment by vcaesar** [comment]
Someone verified macos 10.11, please update first. Any version of libpng 1.6 can.
